version: 2
registries:
 npm-registry:
   type: npm-registry
   url: https://npm.pkg.github.com
   token: ${{secrets.GH_TOKEN}}

updates:
 - package-ecosystem: "github-actions"
   directory: "/"
   schedule:
     interval: "weekly"
     time: "09:20"
     day: "tuesday"

 - package-ecosystem: "npm"
   directory: "/"
   registries:
     - npm-registry
   schedule:
     interval: "weekly"
     time: "09:20"
     day: "tuesday"
   open-pull-requests-limit: 3