version: 2
registries:
 npm-registry:
   type: npm-registry
   url: https://npm.pkg.github.com
   token: ${{secrets.GH_TOKEN}}

updates:
 - package-ecosystem: "github-actions"
   directory: "/"
   schedule:
     interval: "weekly"
     time: "16:30"
     day: "friday"

 - package-ecosystem: "npm"
   directory: "/"
   registries:
     - npm-registry
   schedule:
     interval: "weekly"
     time: "16:30"
     day: "friday"
   open-pull-requests-limit: 3
