export const HOME_SLUG = 'home'
export const ARTISTS_SLUG = 'artists'
export const EXHIBITIONS_SLUG = 'exhibitions'
export const AVAILABLE_ARTWORKS_SLUG = '/available-artworks'
export const FAIRS_SLUG = 'fairs'
export const NEWS_SLUG = 'news'
export const SUBSCRIBE_SLUG = 'subscribe'
