export const LEARN_MORE = 'Learn More'
export const VIEW_ALL_TITLE = 'View All'
export const UPCOMING_FAIRS_URL = '/fairs'
export const ARTISTS_URL = '/artists'
export const NEWS_URL = '/news'
export const ONLINE_EXHIBITIONS_URL = '/exhibitions'

export const ONLINE_EXHIBITIONS_TITLE = 'Online Exhibitions'
export const UPCOMING_FAIRS_TITLE = 'Upcoming Fairs'
export const FEATURE_AVAILABLE_WORKS_TITLE = 'Featured Available Works'
export const EXHIBITIONS = 'Exhibitions'
export const FAIRS = 'Fairs'
export const ARTISTS = 'Artists'
export const TALK_TO_US = 'Talk to Us'
export const GET_IN_TOUCH = 'Get in Touch'
