// ============ URLS =============
export const ARTISTS_URL = '/artists'
export const UPCOMING_FAIRS_URL = '/fairs'
export const NEWS_URL = '/news'
export const EXHIBITIONS_URL = '/exhibitions'
export const PAST_EXHIBITIONS_URL = '/exhibitions/past-exhibitions'
export const VIDEOS_URL = '/videos'
export const PODCAST_URL = '/podcast'
export const EXHIBITION_CHECKLIST_URL = '/checklist'
export const EXHIBITION_INSTALLATION_URL = '/installation-views'
export const BOOKS_URL = 'https://www.davidzwirnerbooks.com/'
export const ARTISTS_PRESS_URL = '/press'
export const ARTISTS_SURVEY_URL = '/survey'
export const ARTISTS_GUIDE_URL = '/guide'
export const ARTISTS_EXHIBITIONS_URL = '/exhibitions'
export const ARTISTS_AVAILABLE_WORKS_URL = '/available-works'
export const ARTWORK_URL = '/artworks'
export const PREVIEW_EXIT_URL = '/api/exit-draft'

// ============ COPIES ===========
export const DAVID_ZWIRNER_BOOKS = 'David Zwirner Books'
export const PRE_ORDER_NOW = 'Pre-order Now'
export const LEARN_MORE = 'Learn More'
export const LEARN_MORE_AMP_SUBSCRIBE = 'Learn More & Subscribe'
export const VIEW_ALL_TITLE = 'View All'
export const FEATURED_VIDEOS = 'Featured Videos'
export const FEATURED_PODCAST = 'Featured Podcast'
export const NEWS_AND_PRESS_HIGHLIGHTS = 'News and Press Highlights'
export const WATCH_MORE_VIDEOS = 'Watch More Videos'
export const LISTEN_MORE_PODCAST = 'Listen to More Podcasts'
export const LOCATION = 'Location'
export const READ_MORE = 'Read More'
export const VIEW_MORE = 'View More'
export const ONLINE_EXHIBITIONS_TITLE = 'Online Exhibitions'
export const UPCOMING_FAIRS_TITLE = 'Upcoming Fairs'
export const FEATURE_AVAILABLE_WORKS_TITLE = 'Featured Available Works'
export const FEATURED_NEW_BOOKS = 'Featured New Books'
export const EXHIBITIONS = 'Exhibitions'
export const EXHIBITION = 'Exhibition'
export const UPCOMING = 'Upcoming'
export const INQUIRE = 'Inquire'
export const INTERESTED_IN_THIS_EXHIBITION = 'Interested in this exhibition?'
export const FAIRS = 'Fairs'
export const EXPLORE_NOW = 'Explore now'
export const ARTICLES = 'Articles'
export const SELECTED_PRESS = 'Selected Press'
export const GUIDE = 'Guide'
export const ARTISTS = 'Artists'
export const TALK_TO_US = 'Talk to Us'
export const GET_IN_TOUCH = 'Get in Touch'
export const EXPLORE = 'Explore'
export const CHECKLIST = 'Checklist'
export const INSTALLATION_VIEWS = 'Installation Views'
export const BUY_NOW = 'Buy Now'
export const COMING_SOON = 'Coming Soon'
export const NOW_CLOSED = 'Now Closed'
export const ORDER_NOW = 'Order Now'
export const LISTEN_NOW = 'Listen now'
export const CURRENT = 'Current'
export const MUSEUM_HIGHLIGHTS = 'Museum Highlights'
export const NOW_OPEN = 'Now Open'
export const SUBSCRIBE = 'Subscribe'
export const ALL_LOCATIONS = 'All Locations'
export const ALL_EXHIBITIONS = 'All Exhibitions'
export const INTERESTED_IN = 'Interested in'
export const THIS_ARTWORK = 'this artwork'
export const TO_LEARN_MORE_ABOUT_AVAILABLE_WORKS =
  'To learn more about available works, please provide your contact information'
export const WANT_TO_KNOW_MORE = 'Want to Know More?'
export const TO_LEARN_MORE_ABOUT = 'To learn more about'
export const PLEASE_PROVIDE_YOUR_CONTACT_SHORT = 'please provide your contact information.'
export const PLEASE_PROVIDE_YOUR_CONTACT =
  'please provide your contact information and a member of the gallery will be in touch shortly.'
export const TO_LEARN_MORE_ABOUT_THIS_ARTWORK =
  'To learn more about this artwork, please provide your contact information.'
export const EXIT_PREVIEW = 'Exit Draft View'
export const JOIN_OUR_MAILING_LIST =
  'Join our mailing list to be among the first to receive gallery news'
export const JOIN_OUR_MAILING_LIST_ERROR = 'Failed to send your request'
export const JOIN_OUR_MAILING_LIST_SUCCESS = 'Thank You for Joining Our Mailing List'
export const EXPECT_THE_LATEST_INFORMATION =
  'Expect the latest information from David Zwirner to arrive soon in your Inbox.'
export const EXPLORE_ALL_ARTWORKS = 'Explore all Artworks'
export const EXPLORE_AVAILABLE_WORKS = 'Explore Available Works'
export const LATEST_EXHIBITIONS = 'Latest Exhibitions'
export const EXPLORE_BOOKS = 'Explore Books'
export const EXPLORE_GUIDE = 'Explore Guide'
export const SURVEY = 'Survey'
export const AVAILABLE_WORKS = 'Available Works'
export const TO_LEARN_MORE_ABOUT_AVAILABLE_WORKS_EXTENDED =
  'To learn more about available works, please provide your contact information and a member of the gallery will be in touch shortly.'
export const DOWNLOAD_PRESS_RELEASE = 'Download Press Release'
export const RECAPTCHA_ERROR_MESSAGE = 'reCAPTCHA connect error'
