name: Create pre-release

on:
  push:
    tags:
      - '2[3-9].[01][0-9].[0-3][0-9].[0-2][0-9]' # A calendar version in the "YY.0M.0D.0H" format.

env:
  VERSION: ${{ github.ref_name }}

jobs:
  create_pre_release:
    name: Create pre-release
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out `${{ env.VERSION }}` tag
        uses: actions/checkout@v4

      - name: Check tag is on `main`
        run: |
          BRANCHES=$(git log -1 --format='%D' tags/$VERSION)
          if [[ $BRANCHES != *'origin/main'* ]]; then
            echo '::error title=Wrong branch::The tag must be created on the `main` branch.'
            exit 1
          fi

      - name: Create pre-release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          generate_release_notes: true
